- LICENSE
- README.md
- index.html
adding css, js and README files
> adding the things

- README.md
- history.html
- homepage.html
- hotels.html
- sites.html
> adding to file structure

- assets/css/reset.css
> Max things to do

- .vscode/settings.json
- homepage.html
> nav bar updates

- hotels.html
set up html structure for page
> set up html structure for page

- hotels.html
> added some span tags

- history.html
- homepage.html
- hotels.html
- sites.html
> Adding nav to all html

- assets/css/style.css
- food.html
- history.html
- homepage.html
- sites.html
fixing hotels.html to food.html on all pages
> fixing hotels.html to food.html on all pages

- assets/css/style.css
- food.html
- history.html
- homepage.html
- sites.html
> Navbar MVP

- assets/css/style.css
- food.html
- history.html
- homepage.html
- sites.html
> linking icons

- sites.html
> finished the page

- assets/css/style.css
- history.html
> History alt

- history.html
> Added some style

- assets/css/style.css
- assets/js/homepage.js
- food.html
- homepage.html
- test.json
starting homepage.js file and getting weather API to work
> starting homepage.js file and getting weather API to work

- assets/js/script.js
> trying to fix the fetch

- assets/css/style2.css
- history.html
> css for early history looking good

- assets/css/style.css
- assets/js/homepage.js
- food.html
- homepage.html
weather API data input and placement on html and css
> weather API data input and placement on html and css

- food.html
- homepage.html
fixing weather box on homepage
> fixing weather box on homepage

- assets/css/style2.css
- homepage.html
> styling for homepage is just about done.

- assets/css/style.css
- assets/js/script.js
- food.html
> adding more style to food

- assets/css/style.css
- assets/css/style2.css
- homepage.html
> changing overall colors

- history.html
- sites.html
> small tweaks again

- assets/css/style.css
- assets/css/style2.css
- assets/js/script.js
- food.html
- history.html
- homepage.html
- sites.html
> same nav bars and mobile friendly.

- assets/css/style2.css
- assets/js/homepage.js
> fixed the weather widget

- assets/css/style2.css
- dontlooknate.html
- history.html
- homepage.html
- sites.html
> dontlooknate

- food.html
- history.html
- index.html
- sites.html
> changed homepage to index.html

- assets/css/style2.css
- assets/images/dontlooknate.html
- food.html
- history.html
- index.html
- sites.html
> hidden dont worry about it

- assets/css/style2.css
- assets/js/sites.js
- sites.html
> added the modal to sites page
